Convert build process to CMake + make/nmake to add built in tests and…
AnacondaRecipes/ninja-feedstock pull request #6
Opened 2022-04-20 22:30 UTC by ScottBailey

- Added outputs to build both the existing package (`ninja`) that depends on python and one that does not (`ninja-no-python`).
- Switched from the legacy `configure.py --bootstrap` build to the new CMake builds. This allows us to run ninja's tests and install it in the standard way.

2022-04-21 13:51 UTC, skupr-anaconda approved these changes

2022-04-21 14:24 UTC, varlackc approved these changes
LGTM

2022-04-29 13:20 UTC, cbouss requested changes
Looks good, but I would remove the VS2015 requirement for windows.

2022-04-29 13:20 UTC, cbouss commented on recipe/meta.yaml
>    skip: true  # [win and vc!=14]
I think the restriction on VS2015 only can be removed.
There used to be a run requirement introduced here:
https://github.com/AnacondaRecipes/ninja-feedstock/commit/5194af92468b8baf804da715ecc7830df6972f8d
But this was removed there:
https://github.com/AnacondaRecipes/ninja-feedstock/commit/e0489d9cb6e68e996dad532e0b7694ea6a012d9b

2022-04-29 14:20 UTC, skupr-anaconda approved these changes

2022-04-29 14:35 UTC, cbouss approved these changes
looks good!

2022-04-29 14:36 UTC, merged